<a href="https://colab.research.google.com/github/Shuaib11-Github/shuaib/blob/master/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

x = np.array([1,2,3,4,5])
N = 5
matrix = np.column_stack([x**(N-i-1) for i in range(N)])
matrix

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [2]:
import numpy as np

x = np.array([1,2,3,4,5])
N = 5
matrix1 = np.vander(x,N)
matrix1

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

# Or

In [3]:
import numpy as np

x = np.array([1,2,3,4,5])
matrix2 = np.vander(x)  # returns a square matrix.
matrix2

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.

The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [4]:
def Moving_Window_Average(arr,n,k):
  values = n-k+1
  idx = 0
  i = 0
  while idx < values and i < len(arr)-3:
    sum = 0
    for j in range(i,i+4):
      sum += arr[j]
    y = round(sum//k,2)
    print(y,end = '\n')
    idx += 1
    i += 1

arr = [10,20,30,40,50,60,70,80,90,100]
n = len(arr)
k = 4
print('In Integer format\n')
Moving_Window_Average(arr,n,k)

In Integer format

25
35
45
55
65
75
85


In [5]:
def Moving_Window_Average(arr,n,k):
  values = n-k+1
  idx = 0
  i = 0
  while idx < values and i < len(arr)-3:
    sum = 0
    for j in range(i,i+4):
      sum += arr[j]
    y = round(sum/k,2)
    print(y,end = '\n')
    idx += 1
    i += 1

arr = [10,20,30,40,50,60,70,80,90,100]
n = len(arr)
k = 4
print('In Float format\n')
Moving_Window_Average(arr,n,k)

In Float format

25.0
35.0
45.0
55.0
65.0
75.0
85.0


Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
def Moving_Window_Average(arr,n,k):
  values = n-k+1
  idx = 0
  i = 0
  while idx < values and i < len(arr)-2:
    sum = 0
    for j in range(i,i+3):
      sum += arr[j]
    y = round(sum//k,2)
    print(y,end = '\n')
    idx += 1
    i += 1

arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = len(arr)
k = 3
print('In Integer format\n')
Moving_Window_Average(arr,n,k)

In Integer format

5
4
5
6
9
28
49
72
84
93
116


In [7]:
def Moving_Window_Average(arr,n,k):
  values = n-k+1
  idx = 0
  i = 0
  while idx < values and i < len(arr)-2:
    sum = 0
    for j in range(i,i+3):
      sum += arr[j]
    y = round(sum/k,2)
    print(y,end = '\n')
    idx += 1
    i += 1

arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = len(arr)
k = 3
print('In Float format\n')
Moving_Window_Average(arr,n,k)

In Float format

5.0
4.67
5.67
6.67
9.67
28.67
49.33
72.67
84.0
93.33
116.33


In [8]:
# Using the concept of cumulative sum:
import numpy as np

def moving_avg(arr,n):
  asum = np.cumsum(arr,dtype =float)  # asum has cumsum of all the elements.

  asum[n:] = asum[n:] - asum[:-n]  # asum[3:] and asum[:-3] will give us the cumsum 
                                    # from second three elements till last three elements.

  return asum[n-1:]/n    # as index starts at zero and n being 3 which is the window size,
                         # asum[n-1] gives the cumsum of first three elements and asum[n-1:]
                         # gives the cumsum of the given array and dividing by n gives an 
                         # moving_avg array.

arr = [10,20,30,40,50,60,70,80,90,100]
n = 3
moving_avg(arr,n).round(2)

array([20., 30., 40., 50., 60., 70., 80., 90.])

In [9]:
# Using the concept of cumulative sum:
import numpy as np

def moving_avg(arr,n):
  asum = np.cumsum(arr,dtype =float)  # asum has cumsum of all the elements.

  asum[n:] = asum[n:] - asum[:-n]  # asum[3:] and asum[:-3] will give us the cumsum 
                                    # from second three elements till last three elements.

  return asum[n-1:]/n    # as index starts at zero and n being 3 which is the window size,
                         # asum[n-1] gives the cumsum of first three elements and asum[n-1:]
                         # gives the cumsum of the given array and dividing by n gives an 
                         # moving_avg array.

arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = 3
moving_avg(arr,n).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])