<a href="https://colab.research.google.com/github/Shuaib11-Github/shuaib/blob/master/Pandas_data_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')   
titanic_train

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
151          152         1       1  ...  66.6000    C2         S
152          153         0       3  ...   8.0500   NaN         S
153          154         0       3  ...  14.5000   NaN         S
154          155         0       3  ...   7.3125   NaN         S
155          156         0       1  ...  61.3792   NaN         C

[156 rows x 12 columns]

In [14]:
a = titanic_train.dtypes[titanic_train.dtypes == 'float64'].index
titanic_train[a].describe()
titanic_train[a].head()

Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

In [17]:
sorted(titanic_train['Name'])[5:10:2]

['Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andrew, Mr. Edgardo Samuel',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [18]:
titanic_train.isnull().value_counts()

PassengerId  Survived  Pclass  Name   Sex    Age    SibSp  Parch  Ticket  Fare   Cabin  Embarked
False        False     False   False  False  False  False  False  False   False  True   False       98
                                             True   False  False  False   False  True   False       27
                                             False  False  False  False   False  False  False       27
                                             True   False  False  False   False  False  False        3
                                             False  False  False  False   False  False  True         1
dtype: int64

In [21]:
titanic_train['Pclass'].unique()

array([3, 1, 2])

In [22]:
titanic_train['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [23]:
char = titanic_train['Cabin'].astype(str)
new_char = [Cabin[0] for x in char]
new_char

NameError: ignored

In [ ]:
titanic_train.tail(10)

PassengerId  Survived  Pclass  \
146          147         1       3   
147          148         0       3   
148          149         0       2   
149          150         0       2   
150          151         0       2   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                             Name     Sex   Age  SibSp  Parch  \
146  Andersson, Mr. August Edvard ("Wennerstrom")    male  27.0      0      0   
147              Ford, Miss. Robina Maggie "Ruby"  female   9.0      2      2   
148      Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5      0      2   
149             Byles, Rev. Thomas Roussel Davids    male  42.0      0      0   
150                    Bateman, Rev. Robert James    male  51.0      0      0   
151             Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1      0   
152                              Meo, Mr. Alfonzo    male  55.5      0      0   
153               van Billiard, Mr. Austin Blyler    male  40.5      0      2   
154                         Olsen, Mr. Ole Martin    male   NaN      0      0   
155                   Williams, Mr. Charles Duane    male  51.0      0      1   

          Ticket     Fare Cabin Embarked  
146       350043   7.7958   NaN        S  
147   W./C. 6608  34.3750   NaN        S  
148       230080  26.0000    F2        S  
149       244310  13.0000   NaN        S  
150  S.O.P. 1166  12.5250   NaN        S  
151       113776  66.6000    C2        S  
152   A.5. 11206   8.0500   NaN        S  
153     A/5. 851  14.5000   NaN        S  
154    Fa 265302   7.3125   NaN        S  
155     PC 17597  61.3792   NaN        C

In [ ]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
titanic_train.dtypes == "object"
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
a
titanic_train[a].describe()


Name   Sex  Ticket Cabin Embarked
count                            156   156     156    31      155
unique                           156     2     145    28        3
top     Williams, Mr. Charles Eugene  male  113803  C123        S
freq                               1   100       2     2      110

In [ ]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [ ]:
titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [ ]:
titanic_train.dtypes[titanic_train.dtypes == "object"]


titanic_train.dtypes[titanic_train.dtypes == "object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [ ]:
titanic_train.dtypes[titanic_train.dtypes == "object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [ ]:
list_col = titanic_train.dtypes[titanic_train.dtypes == "object"].index
titanic_train[list_col].describe()

Name   Sex  Ticket Cabin Embarked
count                            156   156     156    31      155
unique                           156     2     145    28        3
top     Williams, Mr. Charles Eugene  male  113803  C123        S
freq                               1   100       2     2      110

In [ ]:
titanic_train[['Name','Sex','Age']]

Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
5                                     Moran, Mr. James    male   NaN
6                              McCarthy, Mr. Timothy J    male  54.0
7                       Palsson, Master. Gosta Leonard    male   2.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0
10                     Sandstrom, Miss. Marguerite Rut  female   4.0
11                            Bonnell, Miss. Elizabeth  female  58.0
12                      Saundercock, Mr. William Henry    male  20.0
13                         Andersson, Mr. Anders Johan    male  39.0
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0
16                                Rice, Master. Eugene    male   2.0
17                        Williams, Mr. Charles Eugene    male   NaN
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0
19                             Masselmani, Mrs. Fatima  female   NaN
20                                Fynney, Mr. Joseph J    male  35.0
21                               Beesley, Mr. Lawrence    male  34.0
22                         McGowan, Miss. Anna "Annie"  female  15.0
23                        Sloper, Mr. William Thompson    male  28.0
24                       Palsson, Miss. Torborg Danira  female   8.0
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0
26                             Emir, Mr. Farred Chehab    male   NaN
27                      Fortune, Mr. Charles Alexander    male  19.0
28                       O'Dwyer, Miss. Ellen "Nellie"  female   NaN
29                                 Todoroff, Mr. Lalio    male   NaN
..                                                 ...     ...   ...
126                                McMahon, Mr. Martin    male   NaN
127                          Madsen, Mr. Fridtjof Arne    male  24.0
128                                  Peter, Miss. Anna  female   NaN
129                                 Ekstrom, Mr. Johan    male  45.0
130                               Drazenoic, Mr. Jozef    male  33.0
131                     Coelho, Mr. Domingos Fernandeo    male  20.0
132     Robins, Mrs. Alexander A (Grace Charity Laury)  female  47.0
133      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0
134                     Sobey, Mr. Samuel James Hayden    male  25.0
135                                 Richard, Mr. Emile    male  23.0
136                       Newsom, Miss. Helen Monypeny  female  19.0
137                        Futrelle, Mr. Jacques Heath    male  37.0
138                                Osen, Mr. Olaf Elon    male  16.0
139                                 Giglio, Mr. Victor    male  24.0
140                      Boulos, Mrs. Joseph (Sultana)  female   NaN
141                           Nysten, Miss. Anna Sofia  female  22.0
142  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...  female  24.0
143                                Burke, Mr. Jeremiah    male  19.0
144                         Andrew, Mr. Edgardo Samuel    male  18.0
145                       Nicholls, Mr. Joseph Charles    male  19.0
146       Andersson, Mr. August Edvard ("Wennerstrom")    male  27.0
147                   Ford, Miss. Robina Maggie "Ruby"  female   9.0
148           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5
149                  Byles, Rev. Thomas Roussel Davids    male  42.0
150                         Bateman, Rev. Robert James    male  51.0
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0
152                                   Meo, Mr. A

In [ ]:
sorted(titanic_train["Name"])[5:10:2]# Check the first 15 sorted names

['Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andrew, Mr. Edgardo Samuel',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [ ]:
titanic_train["Name"].describe()

count                              156
unique                             156
top       Williams, Mr. Charles Eugene
freq                                 1
Name: Name, dtype: object

In [ ]:
titanic_train[["Ticket"]][4:9]

Ticket
4  373450
5  330877
6   17463
7  349909
8  347742

In [ ]:
titanic_train["Ticket"].describe()
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
titanic_train["sudh"]="sdffs"
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  test   sudh  
0      0         A/5 21171   7.2500   NaN        S     0  sdffs  
1      0          PC 17599  71.2833   C85        C     0  sdffs  
2      0  STON/O2. 3101282   7.9250   NaN        S     0  sdffs  
3      0            113803  53.1000  C123        S     0  sdffs  
4      0            373450   8.0500   NaN        S     0  sdffs

In [ ]:
titanic_train["Cabin"][0:15]       # Check the first 15 tickets

0      NaN
1      C85
2      NaN
3     C123
4      NaN
5      NaN
6      E46
7      NaN
8      NaN
9      NaN
10      G6
11    C103
12     NaN
13     NaN
14     NaN
Name: Cabin, dtype: object

In [ ]:
titanic_train.dtypes# Check number of unique cabins

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
test             int64
dtype: object

In [ ]:
titanic_train["Survived"]

0      0
1      1
2      1
3      1
4      0
5      0
6      0
7      0
8      1
9      1
10     1
11     1
12     0
13     0
14     0
15     1
16     0
17     1
18     0
19     1
20     0
21     1
22     1
23     1
24     0
25     1
26     0
27     0
28     1
29     0
      ..
126    0
127    1
128    1
129    0
130    0
131    0
132    0
133    1
134    0
135    0
136    1
137    0
138    0
139    0
140    0
141    1
142    1
143    0
144    0
145    0
146    1
147    0
148    0
149    0
150    0
151    1
152    0
153    0
154    0
155    0
Name: Survived, Length: 156, dtype: int64

In [ ]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'test'],
      dtype='object')

In [ ]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare   test  
count  156.000000  156.000000  156.0  
mean     0.397436   28.109587    0.0  
std      0.870146   39.401047    0.0  
min      0.000000    6.750000    0.0  
25%      0.000000    8.003150    0.0  
50%      0.000000   14.454200    0.0  
75%      0.000000   30.371850    0.0  
max      5.000000  263.000000    0.0

In [ ]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])

new_Pclass

[90, dfsf, 90, dfsf, 90, ..., dfsf, 90, 90, 90, dfsf]
Length: 156
Categories (3, object): [dfsf, 9, 90]

In [ ]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])
new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [ ]:
titanic_train["Cabin"].unique()   # Check unique cabins

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [ ]:
import numpy as np 
char_cabin = titanic_train["Cabin"].astype(str) # Convert data to str

new_Cabin = [cabin[0] for cabin in char_cabin] # Take first letter

new_Cabin = pd.Categorical(new_Cabin)
#new_Cabin
new_Cabin


[n, C, n, C, n, ..., C, n, n, n, n]
Length: 156
Categories (8, object): [A, B, C, D, E, F, G, n]

In [ ]:
titanic_train["Cabin"] = new_Cabin
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  test   sudh Cabin1  
0      0         A/5 21171   7.2500     n        S     0  sdffs      n  
1      0          PC 17599  71.2833     C        C     0  sdffs      C  
2      0  STON/O2. 3101282   7.9250     n        S     0  sdffs      n  
3      0            113803  53.1000     C        S     0  sdffs      C  
4      0            373450   8.0500     n        S     0  sdffs      n

In [ ]:
titanic_train["Age"].isnull() 

0      False
1      False
2      False
3      False
4      False
5       True
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17      True
18     False
19      True
20     False
21     False
22     False
23     False
24     False
25     False
26      True
27     False
28      True
29      True
       ...  
126     True
127    False
128     True
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140     True
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154     True
155    False
Name: Age, Length: 156, dtype: bool

In [ ]:
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154]),)

In [ ]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88]),)

In [ ]:
titanic_train.iloc[np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))]

PassengerId  Survived Pclass                            Name     Sex  \
27           28         0   dfsf  Fortune, Mr. Charles Alexander    male   
88           89         1   dfsf      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare Cabin Embarked  test   sudh Cabin1  
27  19.0      3      2  19950  263.0     C        S     0  sdffs      C  
88  23.0      3      2  19950  263.0     C        S     0  sdffs      C

In [ ]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([27, 88]),)

In [ ]:
len(missing[0])

30

In [ ]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]
titanic_train["Family"]
most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family

(array([59, 71]),)

In [ ]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]

most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family
titanic_train.iloc[most_family]

PassengerId  Survived  Pclass                                Name     Sex  \
59           60         0       3  Goodwin, Master. William Frederick    male   
71           72         0       3          Goodwin, Miss. Lillian Amy  female   

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked  test Cabin1  Family  
59  11.0      5      2  CA 2144  46.9   NaN        S     0      n       7  
71  16.0      5      2  CA 2144  46.9   NaN        S     0      n       7

In [ ]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)
pd.Series(my_data, index=labels)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}


a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
print ("\nHolding numerical data\n",'-'*25, sep='')
print(pd.Series(arr)[1])



Holding numerical data
-------------------------
20


In [ ]:
print ("\nHolding text labels\n",'-'*20, sep='')
print(pd.Series(labels))



Holding text labels
--------------------
0    a
1    b
2    c
dtype: object


In [ ]:

d = {'a':"kjhk",'b':20,'c':30}
d.items
pd.DataFrame(d,index = ['a','b','c'])

a   b   c
a  kjhk  20  30
b  kjhk  20  30
c  kjhk  20  30

In [ ]:
print ("\nHolding objects from a dictionary\n",'-'*40, sep='')
print(pd.Series([type, sum, max]))


Holding objects from a dictionary
----------------------------------------
0             <class 'type'>
1    <built-in function sum>
2    <built-in function max>
dtype: object


In [ ]:
ser1 = pd.Series([1,2,3,4],index = [2,4,6,8])
ser2 = pd.Series([1,2,5,4],['CA', 'OR', 'NV', 'AZ'])
ser1

2    1
4    2
6    3
8    4
dtype: int64

In [ ]:
ser1[0:3:2]


2    1
6    3
dtype: int64

In [ ]:
print ("\nIndexing by number (positional value in the series)\n",'-'*52, sep='')
print("Value for CA in ser1:", ser1[0])
print("Value for AZ in ser1:", ser1[3])
print("Value for NV in ser2:", ser2[2])
ser1


Indexing by number (positional value in the series)
----------------------------------------------------
Value for CA in ser1: 1
Value for AZ in ser1: 4
Value for NV in ser2: 5


CA    1
OR    2
CO    3
AZ    4
dtype: int64

In [ ]:
print ("\nIndexing by a range\n",'-'*25, sep='')
print ("Value for OR, CO, and AZ in ser1:\n", ser1[0:3:2], sep='')


Indexing by a range
-------------------------
Value for OR, CO, and AZ in ser1:
100    1
CO     3
dtype: int64


In [ ]:
ser1 = pd.Series([1,2,3,4],['CA', 'OR', 'CO', 'CA'])
ser2 = pd.Series([1,2,5,4],['CA', 'NV', 'AZ','OR'])
ser3 = ser1+ser2
ser3

AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

In [ ]:
print ("\nAfter adding the two series, the result looks like this...\n",'-'*59, sep='')
print(ser3)
print("\nPython tries to add values where it finds common index name, and puts NaN where indices are missing\n")



After adding the two series, the result looks like this...
-----------------------------------------------------------
AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

Python tries to add values where it finds common index name, and puts NaN where indices are missing



In [ ]:
print ("\nThe idea works even for multiplication...\n",'-'*43, sep='')
print (ser1*ser2)



The idea works even for multiplication...
-------------------------------------------
AZ    NaN
CA    1.0
CA    4.0
CO    NaN
NV    NaN
OR    8.0
dtype: float64


In [ ]:
from numpy.random import randn as rn
#np.random.seed(101)
matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
#print("\nThe data frame looks like\n",'-'*45, sep='')
df

W         X         Y         Z
A  0.150705 -0.446910  1.669238 -1.138071
B  0.462929  0.129871  0.128628  1.865870
C  0.783021  0.561695 -1.608215 -0.997146
D  1.124639  0.626070 -0.129314 -0.075665
E  0.133687  1.988570  0.416920 -0.729497

In [ ]:
df.iloc[2]

W    0.783021
X    0.561695
Y   -1.608215
Z   -0.997146
Name: C, dtype: float64

In [ ]:
print("\nType of the pair of columns: ", type(df[['X','Z']]), sep='')
print ("\nSo, for more than one column, the object turns into a DataFrame")


Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>

So, for more than one column, the object turns into a DataFrame


In [ ]:
print("\nThe 'X' column accessed by DOT method (NOT recommended)\n",'-'*55, sep='')
print(df["X"])


The 'X' column accessed by DOT method (NOT recommended)
-------------------------------------------------------
A   -0.446910
B    0.129871
C    0.561695
D    0.626070
E    1.988570
Name: X, dtype: float64


In [ ]:
print("\nA column is created by assigning it in relation to an existing column\n",'-'*75, sep='')
df['New'] = df['X']+df['Z']
df['New (Sum of X and Z)'] = df['X']+df['Z']
print(df)



A column is created by assigning it in relation to an existing column
---------------------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
A  0.150705 -0.446910  1.669238 -1.138071 -1.584981             -1.584981
B  0.462929  0.129871  0.128628  1.865870  1.995741              1.995741
C  0.783021  0.561695 -1.608215 -0.997146 -0.435451             -0.435451
D  1.124639  0.626070 -0.129314 -0.075665  0.550405              0.550405
E  0.133687  1.988570  0.416920 -0.729497  1.259073              1.259073


In [ ]:
df

W         X         Y         Z       New  New (Sum of X and Z)
A  0.150705 -0.446910  1.669238 -1.138071 -1.584981             -1.584981
B  0.462929  0.129871  0.128628  1.865870  1.995741              1.995741
C  0.783021  0.561695 -1.608215 -0.997146 -0.435451             -0.435451
D  1.124639  0.626070 -0.129314 -0.075665  0.550405              0.550405
E  0.133687  1.988570  0.416920 -0.729497  1.259073              1.259073

In [ ]:
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep=' ')
df.drop("C",inplace=True) # Notice the axis=1 option, axis = 0 is default, so one has to change it to 1




A column is dropped by using df.drop() method
 -------------------------------------------------------


In [ ]:
df

W         X         Y         Z       New  New (Sum of X and Z)
A  0.150705 -0.446910  1.669238 -1.138071 -1.584981             -1.584981
B  0.462929  0.129871  0.128628  1.865870  1.995741              1.995741
D  1.124639  0.626070 -0.129314 -0.075665  0.550405              0.550405
E  0.133687  1.988570  0.416920 -0.729497  1.259073              1.259073

In [ ]:
df1=df.drop('A')
print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
print(df1)



A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
B  0.462929  0.129871  0.128628  1.865870  1.995741              1.995741
D  1.124639  0.626070 -0.129314 -0.075665  0.550405              0.550405
E  0.133687  1.988570  0.416920 -0.729497  1.259073              1.259073


In [ ]:
print("\nAn in-place change can be done by making inplace=True in the drop method\n",'-'*75, sep='')
df.drop('New (Sum of X and Z)', axis=1, inplace=True)
print(df)


An in-place change can be done by making inplace=True in the drop method
---------------------------------------------------------------------------
          W         X         Y         Z       New
A  0.150705 -0.446910  1.669238 -1.138071 -1.584981
B  0.462929  0.129871  0.128628  1.865870  1.995741
D  1.124639  0.626070 -0.129314 -0.075665  0.550405
E  0.133687  1.988570  0.416920 -0.729497  1.259073


In [ ]:
### Selecting/indexing Rows
#* Label-based 'loc' method
#* Index (numeric) 'iloc' method
df

W         X         Y         Z       New
A  0.150705 -0.446910  1.669238 -1.138071 -1.584981
B  0.462929  0.129871  0.128628  1.865870  1.995741
D  1.124639  0.626070 -0.129314 -0.075665  0.550405
E  0.133687  1.988570  0.416920 -0.729497  1.259073

In [ ]:
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.iloc[3])



Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

W      0.133687
X      1.988570
Y      0.416920
Z     -0.729497
New    1.259073
Name: E, dtype: float64


In [ ]:
print("\nMultiple rows\n")
print(df.loc[['B','C']])


Multiple rows

          W         X         Y        Z       New
B  0.462929  0.129871  0.128628  1.86587  1.995741
C       NaN       NaN       NaN      NaN       NaN


/Users/sudhanshukumar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  


In [ ]:
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[2])



Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W      1.124639
X      0.626070
Y     -0.129314
Z     -0.075665
New    0.550405
Name: D, dtype: float64


In [ ]:
print("\nMultiple rows\n")
print(df.iloc[[1,2]])


Multiple rows

          W         X         Y         Z       New
B  0.462929  0.129871  0.128628  1.865870  1.995741
D  1.124639  0.626070 -0.129314 -0.075665  0.550405


In [ ]:
#### Subsetting DataFrame

In [ ]:

matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)



In [ ]:
print("\nThe DatFrame\n",'-'*45, sep='')
print(df)



The DatFrame
---------------------------------------------
          W         X         Y         Z
A -0.320697  1.586737 -0.962361  0.984044
B -0.236481 -0.520044 -0.137304 -1.719868
C -0.415743 -0.280577  1.293790 -0.495861
D -0.564725 -1.331318 -1.098884  0.385147
E  1.079266  1.101438  1.097766  0.452282


In [ ]:
print("\nElement at row 'B' and column 'Y' is\n") 
print(df.loc[['B','C'],['Y','W']])



Element at row 'B' and column 'Y' is

          Y         W
B -0.137304 -0.236481
C  1.293790 -0.415743


In [ ]:
print("\nSubset comprising of rows B and D, and columns W and Y, is\n")
df.iloc[[1,2,3],[0,1]]


Subset comprising of rows B and D, and columns W and Y, is



W         X
B -0.236481 -0.520044
C -0.415743 -0.280577
D -0.564725 -1.331318

In [ ]:
print(df.loc[['B','C'],])

          W         X         Y         Z
B -0.236481 -0.520044 -0.137304 -1.719868
C -0.415743 -0.280577  1.293790 -0.495861


In [ ]:
print("\nThe DataFrame\n",'-'*45, sep='')
print(df)



The DataFrame
---------------------------------------------
          W         X         Y         Z
A -0.320697  1.586737 -0.962361  0.984044
B -0.236481 -0.520044 -0.137304 -1.719868
C -0.415743 -0.280577  1.293790 -0.495861
D -0.564725 -1.331318 -1.098884  0.385147
E  1.079266  1.101438  1.097766  0.452282


In [ ]:
print("\nBoolean DataFrame(s) where we are checking if the values are greater than 0\n",'-'*75, sep='')
print(df>0)



Boolean DataFrame(s) where we are checking if the values are greater than 0
---------------------------------------------------------------------------
       W      X      Y      Z
A  False   True  False   True
B  False  False  False  False
C  False  False   True  False
D  False  False  False   True
E   True   True   True   True


In [ ]:
print("\n")
print(df.loc[['A','B','C']]>0)




       W      X      Y      Z
A  False   True  False   True
B  False  False  False  False
C  False  False   True  False


In [ ]:
booldf = df>0
print("\nDataFrame indexed by boolean dataframe\n",'-'*45, sep='')
print(df[booldf])


DataFrame indexed by boolean dataframe
---------------------------------------------
          W         X         Y         Z
A       NaN  1.586737       NaN  0.984044
B       NaN       NaN       NaN       NaN
C       NaN       NaN  1.293790       NaN
D       NaN       NaN       NaN  0.385147
E  1.079266  1.101438  1.097766  0.452282


In [ ]:

import pandas as pd 
import numpy as np
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [ ]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nA new DataFrame\n",'-'*25, sep='')
print(df)



A new DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [ ]:
df[df['Height']>65]

Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [ ]:
print("\nRows with Height > 65 inch\n",'-'*35, sep='')
print(df[df['Height']>65])



Rows with Height > 65 inch
-----------------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160


In [ ]:
df['Height']>65

A     True
B     True
C    False
D     True
E    False
Name: Height, dtype: bool

In [ ]:
booldf1 = df['Height']>65
booldf2 = df['Weight']>145


In [ ]:
print("\nRows with Height > 65 inch and Weight >145 lbs\n",'-'*55, sep='')
print(df[(booldf1) & (booldf2)])



Rows with Height > 65 inch and Weight >145 lbs
-------------------------------------------------------
   Age  Height  Weight
B   42      70     148
D   35      68     160


In [ ]:
print("\nDataFrame with only Age and Weight columns whose Height > 65 inch\n",'-'*68, sep='')
print(df[booldf1][['Age','Weight']])


DataFrame with only Age and Weight columns whose Height > 65 inch
--------------------------------------------------------------------
   Age  Weight
A   22     140
B   42     148
D   35     160


In [ ]:
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']


In [ ]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe DataFrame\n",'-'*25, sep='')
print(df)



The DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152


In [ ]:
print("\nAfter resetting index\n",'-'*35, sep='')
print(df.reset_index())



After resetting index
-----------------------------------
  index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152


In [ ]:
print("\nAfter resetting index with 'drop' option TRUE\n",'-'*45, sep='')
print(df.reset_index(drop=True))
"Student Teacher Engineer Doctor Nurse".split()


After resetting index with 'drop' option TRUE
---------------------------------------------
   Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152


['Student', 'Teacher', 'Engineer', 'Doctor', 'Nurse']

In [ ]:
print("\nAdding a new column 'Profession'\n",'-'*45, sep='')
df['Profession'] = "Student Teacher Engineer Doctor Nurse".split()
print(df)



Adding a new column 'Profession'
---------------------------------------------
   Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse


In [ ]:
print("\nSetting 'Profession' column as index\n",'-'*45, sep='')
print (df.set_index('Profession'))


Setting 'Profession' column as index
---------------------------------------------
            Age  Height  Weight
Profession                     
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152


In [ ]:
#multi-indexing
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))


In [ ]:
print("\nTuple pairs after the zip and list command\n",'-'*45, sep='')
print(hier_index)



Tuple pairs after the zip and list command
---------------------------------------------
[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]


In [ ]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
print("\nIndex hierarchy\n",'-'*25, sep='')
print(hier_index)




Index hierarchy
-------------------------
MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])


In [ ]:
print("\nIndex hierarchy type\n",'-'*25, sep='')
print(type(hier_index))



Index hierarchy type
-------------------------
<class 'pandas.core.indexes.multi.MultiIndex'>


In [ ]:
print("\nCreating DataFrame with multi-index\n",'-'*37, sep='')
#np.random.seed(101)
df1 = pd.DataFrame(data=np.round(rn(6,3)), index= hier_index, columns= ['A','B','C'])
print(df1)



Creating DataFrame with multi-index
-------------------------------------
        A    B    C
G1 1 -0.0  1.0 -0.0
   2  2.0 -1.0  0.0
   3 -0.0 -0.0  1.0
G2 1  0.0 -1.0  0.0
   2  1.0  0.0  1.0
   3  0.0 -1.0 -0.0


In [ ]:
#cross tabulation like pivot table

In [ ]:
print("\nGrabbing a cross-section from outer level\n",'-'*45, sep='')
print(df1.xs('G1'))



Grabbing a cross-section from outer level
---------------------------------------------
     A    B    C
1 -0.0  1.0 -0.0
2  2.0 -1.0  0.0
3 -0.0 -0.0  1.0
